"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import Nav from "@components/Nav";
// import Nav from "@components/Navtwo";

import { ChakraProvider } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <div>{children}</div>
        </ChakraProvider>
      </body>
    </html>
  );
}
